export const FETCH_SERVICES_REQUEST = 'FETCH_SERVICES_REQUEST';
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';
export const FETCH_SERVICES_ERROR = 'FETCH_SERVICES_ERROR';
export const FETCH_PROVIDERS_REQUEST = 'FETCH_PROVIDERS_REQUEST';
export const FETCH_PROVIDERS_SUCCESS = 'FETCH_PROVIDERS_SUCCESS';
export const FETCH_PROVIDERS_ERROR = 'FETCH_PROVIDERS_ERROR';
export const UPDATE_SELECTED_SERVICE = 'UPDATE_SELECTED_SERVICE';